# Generated by Django 5.0.3 on 2025-02-12 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auditorium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(blank=True, max_length=100)),
                ('groom_family_name', models.CharField(blank=True, max_length=100)),
                ('groom_address', models.CharField(blank=True, max_length=255)),
                ('groom_phone_number', models.CharField(blank=True, max_length=15)),
                ('groom_church_name', models.CharField(blank=True, max_length=100)),
                ('groom_father_name', models.CharField(blank=True, max_length=100)),
                ('groom_mother_name', models.CharField(blank=True, max_length=100)),
                ('groom_date_of_birth', models.DateField(blank=True, null=True)),
                ('bride_name', models.CharField(blank=True, max_length=100)),
                ('bride_family_name', models.CharField(blank=True, max_length=100)),
                ('bride_address', models.CharField(blank=True, max_length=255)),
                ('bride_phone_number', models.CharField(blank=True, max_length=15)),
                ('bride_church_name', models.CharField(blank=True, max_length=100)),
                ('bride_father_name', models.CharField(blank=True, max_length=100)),
                ('bride_mother_name', models.CharField(blank=True, max_length=100)),
                ('bride_date_of_birth', models.DateField(blank=True, null=True)),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('held_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.auditorium')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
