# Generated by Django 5.0.3 on 2025-02-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_marriage_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage_record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='marriage_record',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marriage_record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
