# Generated by Django 5.0.3 on 2025-02-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_donation_house_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_donation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
