# Generated by Django 5.0.3 on 2025-03-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='death_record',
            name='priest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
